name: build_Qt6.10.2_MinGW1310_64

on: workflow_dispatch
#on: [push, pull_request]

env:
  QT_VERSION: 6.10.2
  QT_VERSION2: '6.10'
  FILE_NAME: static-Release_mingw1310_64

jobs:
  windows_mingw64_static_release:
    runs-on: windows-latest

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v6

    # 安装python
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        architecture: 'x64'

    # 安装 MinGW1310_64    
    - name: Setup MinGW64
      run: |
        cd ..  #Directory: D:\a\buildQt
        curl -L -o mingw1310.7z https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/tools_mingw1310/qt.tools.win64_mingw1310/13.1.0-202407240918mingw1310.7z
        7z x D:\a\buildQt\mingw1310.7z -oD:\a\buildQt

    # 安装 Ninja
    - name: Setup Ninja
      run: |
        cd ..  #Directory: D:\a\buildQt
        mkdir -p ninja
        curl -L -o ninja.zip https://github.com/ninja-build/ninja/releases/download/v1.13.2/ninja-win.zip
        unzip -q ninja.zip -d ./ninja

    # 构建Qt
    - name: Build Qt
      run: |
        #ls     #Directory: D:\a\buildQt\buildQt(即仓库目录)
        #D:\a\buildQt                                上级目录，这里当做根目录
        #D:\a\buildQt\Qt                             Qt目录
        #D:\a\buildQt\Qt\${{env.QT_VERSION}}         Qt目录源代码和build文件夹存放目录
        #D:\a\buildQt\Qt\${{env.QT_VERSION}}-static  Qt安装目录
        
        # 创建文件夹
        cd ..  #Directory: D:\a\buildQt
        mkdir -p Qt

        # 创建文件夹
        cd Qt   #Directory: D:\a\buildQt\Qt
        mkdir -p ${{env.QT_VERSION}}
        mkdir -p ${{env.QT_VERSION}}-static

        # 下载源代码并解压，源代码目录D:\a\buildQt\Qt\${{env.QT_VERSION}}\XXX
        curl -L -o qt-everywhere-src.zip https://download.qt.io/official_releases/qt/${{env.QT_VERSION2}}/${{env.QT_VERSION}}/single/qt-everywhere-src-${{env.QT_VERSION}}.zip
        unzip -q qt-everywhere-src.zip -d ./${{env.QT_VERSION}}

        # 调用编译脚本
        cmd.exe /c "call `"D:\a\buildQt\buildQt\buildQt6\build-Qt6mingw1310_64.cmd`""

    # 打包
    - name: Package binaries
      run: |
        #ls     #Directory: D:\a\buildQt\buildQt(即仓库目录)
        7z a Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z ../Qt/${{env.QT_VERSION}}-static -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        path: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z

    # 发布
    - name: TempRelease
      uses: softprops/action-gh-release@v2
      with:
        tag_name: temp_Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        release_name: TempRelease_Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}
        files: Qt_${{env.QT_VERSION}}-${{env.FILE_NAME}}.7z
